name: Build extension on code changes
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_binaries:
    uses: Zylann/godot_voxel/.github/workflows/extension_builds.yml@master
    # with:
    #   float-precisions: [single, double]
